// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BlogArticle: typeof import('./src/components/BlogArticle/index.vue')['default']
    BlogArticleItem: typeof import('./src/components/BlogArticleItem/index.vue')['default']
    BriefIntroductionCard: typeof import('./src/components/BriefIntroductionCard/index.vue')['default']
    ClassificationCard: typeof import('./src/components/ClassificationCard/index.vue')['default']
    ContactInformation: typeof import('./src/components/ContactInformation/index.vue')['default']
    EditorView: typeof import('./src/components/EditorView/index.vue')['default']
    ElBacktop: typeof import('element-plus/es')['ElBacktop']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    HomeHeader: typeof import('./src/components/HomeHeader/index.vue')['default']
    LinksCard: typeof import('./src/components/LinksCard/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TagsCard: typeof import('./src/components/TagsCard/index.vue')['default']
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
