// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BlogArticleItem: typeof import('./src/components/BlogArticleItem/index.vue')['default']
    BriefIntroductionCard: typeof import('./src/components/BriefIntroductionCard/index.vue')['default']
    ClassificationCard: typeof import('./src/components/ClassificationCard/index.vue')['default']
    ContactInformation: typeof import('./src/components/ContactInformation/index.vue')['default']
    ElBacktop: typeof import('element-plus/es')['ElBacktop']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElInput: typeof import('element-plus/es')['ElInput']
    HomeHeader: typeof import('./src/components/HomeHeader/index.vue')['default']
    LinksCard: typeof import('./src/components/LinksCard/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TagsCard: typeof import('./src/components/TagsCard/index.vue')['default']
  }
}
