// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    '>': typeof import('./src/components/HomeView/    <MainItem       v-for="mainItem in mainItemList"       :key="mainItem.ID"       :data="mainItem"     />/index.vue')['default']
    BlogArticleItem: typeof import('./src/components/BlogArticleItem/index.vue')['default']
    BriefIntroduction: typeof import('./src/components/HomeView/BriefIntroduction/index.vue')['default']
    BriefIntroductionCard: typeof import('./src/components/BriefIntroductionCard/index.vue')['default']
    ClassificationCard: typeof import('./src/components/ClassificationCard/index.vue')['default']
    ContactInformation: typeof import('./src/components/ContactInformation/index.vue')['default']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElBacktop: typeof import('element-plus/es')['ElBacktop']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElFooter: typeof import('element-plus/es')['ElFooter']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElMenuItemGroup: typeof import('element-plus/es')['ElMenuItemGroup']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElTag: typeof import('element-plus/es')['ElTag']
    HomeAside: typeof import('./src/components/HomeView/HomeAside/index.vue')['default']
    HomeHeader: typeof import('./src/components/HomeHeader/index.vue')['default']
    HomeView: typeof import('./src/components/HomeView/index.vue')['default']
    LinksCard: typeof import('./src/components/LinksCard/index.vue')['default']
    Main: typeof import('./src/components/Main/index.vue')['default']
    MainItem: typeof import('./src/components/MainItem/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TagsCard: typeof import('./src/components/TagsCard/index.vue')['default']
  }
}
